#!/usr/bin/env python3
"""Stage 6 of p_yaml_to_site.md — place every image the YAML's
should_be_on_pages says belongs on a topic page, onto that page.

Writes a regenerated block between the CK_PLACED_IMAGES markers at the BOTTOM of
each host page. Outside the markers the page stays byte-identical. Each placed
image is hosted from the served static copy (/img/evidence/<sha>.<ext>), carries
its IPFS CID as data-cid, and is wrapped in an anchor to its own Photos image
page. Pinned-and-file-less entries are served from the IPFS gateway instead.

Never touches images/images.yaml, sidebars.ts, pages.csv, or anything under
site/docs/Photos.

Run with --apply to write. Default is a dry run that only reports.
"""
import csv, os, re, shutil, sys
import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sanitize_common import sanitize_prose, is_invisible

HOME = os.path.expanduser("~")
ROOT = os.path.join(HOME, "BGit/Bryan_git/charlie-kirk")
YAML_PATH = os.path.join(ROOT, "images/images.yaml")
DOCS = os.path.join(ROOT, "site/docs")
PHOTOS = os.path.join(DOCS, "Photos")
STATIC_IMG_DIR = os.path.join(ROOT, "site/internals/static/img/evidence")
CSS_FILE = os.path.join(ROOT, "site/internals/src/css/custom.css")
PAGES_CSV = os.path.join(ROOT, "pages.csv")
EXCLUDE_FILE = os.path.join(ROOT, "image_planning/exclude_images.txt")

APPLY = "--apply" in sys.argv
PER_PAGE_CAP = 12
MAX_STATIC_BYTES = 2 * 1024 * 1024

START = "{/* CK_PLACED_IMAGES_START — generated by image_planning/generator/place_should_be_images.py. Do not hand-edit inside these markers. */}"
END = "{/* CK_PLACED_IMAGES_END */}"
BLOCK_RE = re.compile(
    r"\n*\{/\* CK_PLACED_IMAGES_START.*?\{/\* CK_PLACED_IMAGES_END \*/\}\n*",
    re.S)


def expu(p):
    return os.path.expanduser(str(p)) if p else ""


# ---------------------------------------------------------------- exclusion gate
# Union of images/ban_images.csv and image_planning/exclude_images.txt — see the
# repo charter, "Banned Media". A banned image is never placed on any page.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ban_set import load_ban_idents          # noqa: E402

BANNED_IDENTS, _UNBANNED = load_ban_idents(EXCLUDE_FILE)
EXCLUDED = {i for i in BANNED_IDENTS if re.fullmatch(r"[0-9a-f]{64}", i)}


def entry_is_banned(inner):
    for k in ("sha256", "cid", "file_path"):
        v = str(inner.get(k) or "").strip()
        if v and v in BANNED_IDENTS:
            return True
    return False

# ---------------------------------------------------------------- pages.csv urls
csv_url_by_file = {}
with open(PAGES_CSV, newline="", encoding="utf-8") as f:
    for r in csv.DictReader(f):
        if r.get("file_path"):
            csv_url_by_file[r["file_path"]] = r.get("url_path") or ""


def image_page_url(image_page):
    p = expu(image_page)
    if not p.startswith(DOCS + os.sep):
        return None
    rel = os.path.relpath(p, DOCS)
    url = "/" + re.sub(r"\.mdx?$", "", rel)
    csv_url = csv_url_by_file.get("site/docs/" + rel)
    return csv_url if csv_url else url


# ---------------------------------------------------------------- static copies
static_by_sha = {}
if os.path.isdir(STATIC_IMG_DIR):
    for fn in os.listdir(STATIC_IMG_DIR):
        stem, ext = os.path.splitext(fn)
        if re.fullmatch(r"[0-9a-f]{64}", stem):
            static_by_sha[stem] = ext.lower()


def ensure_static(sha, file_path):
    """Return '/img/evidence/<sha><ext>' if a served copy exists or can be made."""
    if sha in static_by_sha:
        return "/img/evidence/" + sha + static_by_sha[sha]
    src = expu(file_path)
    if not src or not os.path.isfile(src):
        return None
    ext = os.path.splitext(src)[1].lower() or ".jpg"
    dst = os.path.join(STATIC_IMG_DIR, sha + ext)
    if APPLY:
        os.makedirs(STATIC_IMG_DIR, exist_ok=True)
        if os.path.getsize(src) > MAX_STATIC_BYTES:
            try:
                from PIL import Image
                im = Image.open(src)
                im.thumbnail((2000, 2000))
                if im.mode in ("RGBA", "P") and ext in (".jpg", ".jpeg"):
                    im = im.convert("RGB")
                im.save(dst, quality=85)
            except Exception:
                shutil.copy2(src, dst)
        else:
            shutil.copy2(src, dst)
    static_by_sha[sha] = ext
    return "/img/evidence/" + sha + ext


# ---------------------------------------------------------------- yaml walk
with open(YAML_PATH, encoding="utf-8") as f:
    doc = yaml.safe_load(f)


def child_lists(node):
    for k, v in node.items():
        if re.fullmatch(r"level_\d+", k) and isinstance(v, list):
            yield int(k.split("_")[1]), v


entries = []


def rec(items, lvl):
    for it in items:
        node = it.get(f"level_{lvl}")
        if not isinstance(node, dict):
            continue
        for kind in ("images", "videos"):
            for m in node.get(kind) or []:
                inner = m.get("image") or m.get("video")
                if isinstance(inner, dict):
                    entries.append((inner, kind))
        for nl, arr in child_lists(node):
            rec(arr, nl)


rec(doc["level_3"], 3)


def first_sentence(text, limit=220):
    t = sanitize_prose(text or "")
    if not t:
        return ""
    m = re.search(r"(?<=[.!?])\s", t)
    s = t[:m.start() + 1] if m else t
    if len(s) > limit:
        s = s[:limit].rsplit(" ", 1)[0].rstrip(",;:") + "…"
    return s


def esc_attr(s):
    return (sanitize_prose(s).replace("&", "&amp;").replace('"', "&quot;")
            .replace("<", "&lt;").replace(">", "&gt;"))


def esc_text(s):
    # MDX treats { } as expression delimiters and < as a tag opener.
    return (sanitize_prose(s).replace("{", "&#123;").replace("}", "&#125;")
            .replace("<", "&lt;").replace(">", "&gt;"))


# ---------------------------------------------------------------- plan
stat_static = stat_copied = stat_ipfs = stat_unresolved = 0
no_image_page = 0
dead_paths = []
skipped_excluded = 0
host_map = {}
n_with_sb = 0

for inner, kind in entries:
    sb = inner.get("should_be_on_pages") or []
    if not sb:
        continue
    n_with_sb += 1
    sha = inner.get("sha256") or ""
    if sha in EXCLUDED or entry_is_banned(inner):
        skipped_excluded += 1
        continue
    ip = inner.get("image_page") or ""
    url = image_page_url(ip) if ip else None
    if not url:
        no_image_page += 1
        continue

    cid = inner.get("cid") or ""
    had_static = sha in static_by_sha
    src = ensure_static(sha, inner.get("file_path"))
    if src:
        if had_static:
            stat_static += 1
        else:
            stat_copied += 1
    elif cid and inner.get("ipfs_pinned"):
        src = f"https://ipfs.io/ipfs/{cid}"
        stat_ipfs += 1
    else:
        stat_unresolved += 1
        continue

    if kind == "videos":
        continue  # this stage places images; videos have their own embeds

    desc = inner.get("ai_description") or ""
    ent = {
        "sha": sha,
        "cid": cid,
        "src": src,
        "url": url,
        "alt": esc_attr(first_sentence(desc, 180)) or "Evidence image",
        "caption": esc_text(first_sentence(desc, 220)) or "Evidence image.",
    }

    seen = set()
    for hp in sb:
        page = hp.get("page") if isinstance(hp, dict) else hp
        p = expu(page)
        if not p or p in seen:
            continue
        seen.add(p)
        if not os.path.isfile(p):
            dead_paths.append((sha[:8], str(page)))
            continue
        if p.startswith(PHOTOS + os.sep):
            continue
        host_map.setdefault(p, []).append(ent)

# ---------------------------------------------------------------- emit
def render_block(items):
    out = [START, "", "## Images", "",
           '<div className="ck-placed-gallery">', ""]
    for e in items:
        out.append('<figure className="ck-placed-figure">')
        cid_attr = f' data-cid="{e["cid"]}"' if e["cid"] else ""
        out.append(f'  <a href="{e["url"]}">'
                   f'<img className="ck-placed-img" src="{e["src"]}" '
                   f'alt="{e["alt"]}"{cid_attr} loading="lazy" /></a>')
        out.append(f'  <figcaption className="ck-placed-caption">{e["caption"]} '
                   f'<a href="{e["url"]}">Full write-up &rarr;</a></figcaption>')
        out.append("</figure>")
        out.append("")
    out.append("</div>")
    out.append("")
    out.append(END)
    return "\n".join(out)


created = replaced = removed = 0
placed = skipped_present = 0
over_cap = []
pages_edited = 0
preexisting_invisible = []

for p in sorted(host_map):
    with open(p, encoding="utf-8") as f:
        text = f.read()
    orig = text
    stripped = BLOCK_RE.sub("\n", text)

    items, dropped = [], 0
    for e in host_map[p]:
        if (e["sha"] and e["sha"] in stripped) or (e["cid"] and e["cid"] in stripped):
            dropped += 1
            continue
        if any(x["sha"] == e["sha"] for x in items):
            continue
        items.append(e)
    skipped_present += dropped

    # Count DISTINCT images already on the page, not <img> tags — an embed that
    # is both an anchor href and an img src must not count twice.
    existing_embeds = len(set(re.findall(r"/img/evidence/([0-9a-f]{64})", stripped)))
    room = max(0, PER_PAGE_CAP - existing_embeds)
    if len(items) > room:
        over_cap.append((os.path.relpath(p, ROOT), len(items) - room))
        items = items[:room]

    had_block = bool(BLOCK_RE.search(text))
    if items:
        block = render_block(items)
        if had_block:
            text = BLOCK_RE.sub("\n\n" + block + "\n", text, count=1)
            replaced += 1
        else:
            text = stripped.rstrip("\n") + "\n\n" + block + "\n"
            created += 1
        placed += len(items)
    else:
        if had_block:
            text = stripped.rstrip("\n") + "\n"
            removed += 1
        else:
            continue

    # Sanitization applies to what THIS stage emits. The rest of the page must
    # stay byte-identical, so a pre-existing invisible char elsewhere in the
    # file is reported, not "fixed" here.
    if items:
        for ch in block:
            if ch not in ("\n", "\t") and is_invisible(ord(ch)):
                raise SystemExit(f"SANITIZATION FAILURE: emitted block for {p}")
    if any(ch not in ("\n", "\t") and is_invisible(ord(ch)) for ch in stripped):
        preexisting_invisible.append(os.path.relpath(p, ROOT))

    if text != orig:
        pages_edited += 1
        if APPLY:
            with open(p, "w", encoding="utf-8") as f:
                f.write(text)

# ---------------------------------------------------------------- css
CSS_START = "/* CK_PLACED_IMAGES_START */"
CSS_END = "/* CK_PLACED_IMAGES_END */"
CSS_BLOCK = CSS_START + """
/* Stage 6 of p_yaml_to_site.md — the gallery of images placed on a topic page
   from the YAML's should_be_on_pages. A responsive grid at the bottom of the
   page; each tile is a fixed-height thumbnail that never crops (object-fit:
   contain) and clicks through to that image's own Photos page. */
.ck-placed-gallery {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
  gap: 1.25rem;
  margin: 1rem 0 2rem 0;
  clear: both;
}
.ck-placed-figure {
  margin: 0;
  display: flex;
  flex-direction: column;
}
.ck-placed-figure > a {
  display: block;
  background: var(--ifm-background-surface-color, #fff);
  box-shadow: 0 1px 8px rgba(0, 0, 0, 0.28);
  line-height: 0;
}
.ck-placed-img {
  display: block;
  width: 100%;
  height: 190px;
  object-fit: contain;
  background: var(--ifm-background-surface-color, #fff);
}
.ck-placed-caption {
  font-size: 0.82rem;
  line-height: 1.35;
  margin-top: 0.45rem;
  color: var(--ifm-color-emphasis-700);
}
@media (max-width: 996px) {
  .ck-placed-gallery { grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); }
  .ck-placed-img { height: 150px; }
}
""" + CSS_END

css_action = "unchanged"
if os.path.exists(CSS_FILE):
    css = open(CSS_FILE, encoding="utf-8").read()
    pat = re.compile(re.escape(CSS_START) + r".*?" + re.escape(CSS_END), re.S)
    if pat.search(css):
        new_css = pat.sub(lambda m: CSS_BLOCK, css)
        css_action = "replaced" if new_css != css else "unchanged"
    else:
        new_css = css.rstrip("\n") + "\n\n" + CSS_BLOCK + "\n"
        css_action = "created"
    if APPLY and new_css != css:
        open(CSS_FILE, "w", encoding="utf-8").write(new_css)

# ---------------------------------------------------------------- report
print("============================")
print("STAGE 6 COMPLETE", "(APPLIED)" if APPLY else "(DRY RUN)")
print(f"Images with should_be_on_pages: {n_with_sb}   "
      f"placements planned: {sum(len(v) for v in host_map.values())} "
      f"over {len(host_map)} pages")
print(f"Src resolution: {stat_static} static / {stat_copied} copied-then-static / "
      f"{stat_ipfs} IPFS gateway / {stat_unresolved} unresolvable")
print(f"Pages edited: {pages_edited}   blocks created: {created}   "
      f"blocks replaced: {replaced}   blocks removed: {removed}")
print(f"Images placed: {placed}   skipped as already embedded: {skipped_present}")
print(f"Excluded images skipped: {skipped_excluded}")
print(f"Over the {PER_PAGE_CAP}-per-page cap: {len(over_cap)}")
for pg, n in sorted(over_cap, key=lambda x: -x[1])[:15]:
    print(f"   - {pg} -> {n} over")
print(f"Missing image_page: {no_image_page}   "
      f"should_be_on_pages paths that no longer exist: {len(dead_paths)}")
for sha, pg in dead_paths[:15]:
    print(f"   - {sha} -> {pg}")
print(f"CSS block: {css_action}")
if preexisting_invisible:
    print(f"Host pages carrying pre-existing invisible Unicode (not touched here): "
          f"{len(preexisting_invisible)}")
    for pg in preexisting_invisible[:10]:
        print(f"   - {pg}")
print("============================")
